AWSTemplateFormatVersion: 2010-09-09

Description: Stack for Amplify App

Parameters:
  AppName:
    Description: App name
    Default: "ext-amplify-develop"
    Type: String
  RoleName:
    Description: Role name
    Default: "AmplifyDevelopRole"
    Type: String
  TagEnv:
    Description: Env name
    Default: "develop"
    Type: String
  OAuthToken:
    Type: String
    Default: "oauthtokent-very-Longish-xxxxxxxxxx-4Hoeen=="
    Description: GitHub access token
    NoEcho: true
  Repository:
    Description: Bitbucket Cloud repository URL for Amplify app
    Default: "https://github.com/dlozynski/ext-amplify"
    Type: String
  MainBranchName:
    Description: Main branch
    Default: "master"
    Type: String
  BackendMasterBranchName:
    Description: Backend master name
    Default: "main"
    Type: String
  BackendDevelopmentBranchName:
    Description: Backend master name
    Default: "stagingva"
    Type: String
  DevelopmentBranchName:
    Description: Development branch
    Default: "staging"
    Type: String
  Environment:
    Description: Backend environment related to this branch
    Default: "master"
    Type: String

Resources:
  AmplifyApp:
    DependsOn:
      - AmplifyRole
    Type: AWS::Amplify::App
    Properties:
      Name:       !Ref AppName
      OauthToken: !Ref OAuthToken
      Repository: !Ref Repository
      Description: "experimental testing for AWS CF"
      EnableBranchAutoDeletion: true
      AutoBranchCreationConfig:
        AutoBranchCreationPatterns:
          - " "
        EnableAutoBranchCreation: false
      BasicAuthConfig:
        EnableBasicAuth: false
        # Password: "test123"
        # Username: "test123"
      CustomRules:
        - Source: "</^[^.]+$|\\.(?!(css|gif|ico|jpg|js|png|txt|svg|woff|woff2|ttf|map|json|webp)$)([^.]+$)/>"
          Status: "200"
          Target: "/index.html"
        # - Source: "/amplify/master"
        #   Status: "301"
        #   Target: "https://eu-west-2.admin.amplifyapp.com/admin/extamplify123abcd/master/home"
        # - Source: "/amplify/staging"
        #   Status: "301"
        #   Target: "https://eu-west-2.admin.amplifyapp.com/admin/extamplify123abcd/staging/home"
      EnvironmentVariables:
        - Name: AMPLIFY_FACEBOOK_CLIENT_ID
          Value: "123856123761321"
        - Name: AMPLIFY_FACEBOOK_CLIENT_SECRET
          Value: "abcda2b8a5d212345678a050a5faeabcd"
        - Name: AMPLIFY_GOOGLE_CLIENT_ID
          Value: "1230046123123-hjb2323i23ihi3ufake.apps.googleusercontent.com"
        - Name: AMPLIFY_GOOGLE_CLIENT_SECRET
          Value: "GOGADGET-ABCDabcd12344312-abcd123"
        - Name: AMPLIFY_AMAZON_CLIENT_ID
          Value: "amzn1.application-oa2-client.1234abcd1234abcd1234"
        - Name: AMPLIFY_AMAZON_CLIENT_SECRET
          Value: "abc1234a12345678899cb13f388c91273152b57beb760add6a123456789asdfghjklfake"
        - Name: SES_EMAIL
          Value: "extamplify.test.001@gmail.com"
        - Name: _LIVE_UPDATES
          Value: '[{"pkg":"@aws-amplify/cli","type":"npm","version":"9.0.0"},{"pkg":"node","type":"nvm","version":"16"},{"pkg":"yarn","type":"npm","version":"latest"}]'
      IAMServiceRole: !GetAtt AmplifyRole.Arn
      BuildSpec: |-
        version: 1
        backend:
          phases:
            build:
              commands:
                - amplifyPush --simple
        frontend:
          phases:
            preBuild:
              commands:
                - npm ci
            build:
              commands:
                - npm run build
          artifacts:
            baseDirectory: build
            files:
              - '**/*'
          cache:
            paths:
              - node_modules/**/*
      Tags:
        - Key: Type
          Value: !Ref TagEnv

# Role for Amplify
  AmplifyRole:
    Type: AWS::IAM::Role
    DeletionPolicy: Delete
    Properties:
      RoleName: !Ref RoleName
      Description: Amplify app IAM role
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/AdministratorAccess-Amplify"
        - "arn:aws:iam::aws:policy/AWSCodeCommitReadOnly"
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - amplify.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: Amplify
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: "amplify:*"
                Resource: "*"

# Branch configuration
  MainAmplifyBranch:
    Type: AWS::Amplify::Branch
    Properties:
      AppId: !GetAtt AmplifyApp.AppId
      BranchName: !Ref MainBranchName
      Description: Main branch for Amplify app
      EnableAutoBuild: true
      EnablePerformanceMode: false
      EnablePullRequestPreview: true
      PullRequestEnvironmentName: "pullreq"
      Stage: "PRODUCTION"
      EnvironmentVariables:
        - Name: USER_BRANCH
          Value: !Ref BackendMasterBranchName
        - Name: AMPLIFY_BACKEND_PULL_ONLY
          Value: "true"
        - Name: AMPLIFY_BACKEND_APP_ID
          Value: !GetAtt AmplifyApp.AppId

  DevelopmentAmplifyBranch:
    Type: AWS::Amplify::Branch
    Properties:
      AppId: !GetAtt AmplifyApp.AppId
      BranchName: !Ref DevelopmentBranchName
      Description: Deployment branch for Amplify app
      EnableAutoBuild: true
      EnablePerformanceMode: false
      EnablePullRequestPreview: false
      Stage: "DEVELOPMENT"
      EnvironmentVariables:
        - Name: USER_BRANCH
          Value: !Ref BackendDevelopmentBranchName
        - Name: AMPLIFY_BACKEND_PULL_ONLY
          Value: "true"
        - Name: AMPLIFY_BACKEND_APP_ID
          Value: !GetAtt AmplifyApp.AppId

Outputs:
  AmplifyAppName:
    Description: "Name of role used in Amplify"
    Value: !Ref AmplifyApp
    Export:
      Name: !Join
          - ""
          - - "amplify-im-main-"
            - !Ref TagEnv
            - "-app-name"

  AmplifyAppId:
    Description: "Name of role used in Aplify"
    Value: !GetAtt AmplifyApp.AppId
    Export:
      Name: !Join
          - ""
          - - "amplify-im-main-"
            - !Ref TagEnv
            - "-app-id"

  AmplifyRoleName:
    Description: "Name of role used in Aplify"
    Value: !Ref AmplifyRole
    Export:
      Name: !Join
          - ""
          - - "amplify-"
            - !Ref RoleName
            - ":iam:"
            - !Ref TagEnv
            - "-role-name"

  AmplifyRoleArn:
    Description: "ARN of role used in Amplify"
    Value: !GetAtt AmplifyRole.Arn
    Export:
      Name: !Join
          - ""
          - - "amplify-"
            - !Ref RoleName
            - ":iam:"
            - !Ref TagEnv
            - "-role-arn"