---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ $.Chart.Name }}-secret
  labels:
    app: {{ $.Chart.Name }}
stringData:
{{- range $k, $v :=  .Values.secrets }}
  {{$k}}: {{quote $v}}
{{- end }}