---
container:
  image: "12341234.dkr.ecr.eu-west-1.amazonaws.com/theapp-frontend"
  tag: "latest"
  port: 7070
  containerPort: 7070
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 2
  maxSurge: 25%
  maxUnavailable: 25%

ingress:
  hosts:
    - name: minikube.local
  paths:
    - path: /settings
    - path: /subcriptions
    - path: /static
    - path: /sockjs-node
  serviceName: theapp-frontend
  servicePort: 7070
